import json

print(json.dumps({
    "additionalContext": (
        "STOP — plan mode required: "
        '"Implement the following plan:" is auto-generated by Claude Code and is NOT a confirmed go-ahead. '
        "Enter plan mode, present the approach, and wait for explicit user confirmation before touching any file."
    )
}))
